/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  await knex("customers").del();

  await knex("customers").insert([
    {
      id: 1,
      name: "Clarence Daing",
      phone: "555-0001",
      frequent_order: "Americano",
      visits: 5,
    },
    {
      id: 2,
      name: "Sasha Santos",
      phone: "555-0002",
      frequent_order: "Latte",
      visits: 3,
    },
    {
      id: 3,
      name: "Daniel Reyes",
      phone: "555-0003",
      frequent_order: "Cappuccino",
      visits: 4,
    },
    {
      id: 4,
      name: "April Kim",
      phone: "555-0004",
      frequent_order: "Espresso",
      visits: 2,
    },
    {
      id: 5,
      name: "Leo Tran",
      phone: "555-0005",
      frequent_order: "Matcha Latte",
      visits: 3,
    },
    {
      id: 6,
      name: "Nina Park",
      phone: "555-0006",
      frequent_order: "Flat White",
      visits: 6,
    },
    {
      id: 7,
      name: "Jordan Cruz",
      phone: "555-0007",
      frequent_order: "Iced Coffee",
      visits: 1,
    },
    {
      id: 8,
      name: "Miguel Torres",
      phone: "555-0008",
      frequent_order: "Mocha",
      visits: 2,
    },
    {
      id: 9,
      name: "Isabella Lee",
      phone: "555-0009",
      frequent_order: "Caramel Macchiato",
      visits: 4,
    },
    {
      id: 10,
      name: "Haruto Sato",
      phone: "555-0010",
      frequent_order: "Cold Brew",
      visits: 5,
    },
    {
      id: 11,
      name: "Layla Zhang",
      phone: "555-0011",
      frequent_order: "Chai Latte",
      visits: 2,
    },
    {
      id: 12,
      name: "Ethan Walker",
      phone: "555-0012",
      frequent_order: "Iced Americano",
      visits: 3,
    },
    {
      id: 13,
      name: "Liam Scott",
      phone: "555-0013",
      frequent_order: "Cortado",
      visits: 1,
    },
    {
      id: 14,
      name: "Olivia Chen",
      phone: "555-0014",
      frequent_order: "Iced Latte",
      visits: 6,
    },
    {
      id: 15,
      name: "Noah Kim",
      phone: "555-0015",
      frequent_order: "Vanilla Latte",
      visits: 4,
    },
    {
      id: 16,
      name: "Mila Nguyen",
      phone: "555-0016",
      frequent_order: "Pumpkin Spice Latte",
      visits: 2,
    },
    {
      id: 17,
      name: "Jacob Brown",
      phone: "555-0017",
      frequent_order: "Hot Chocolate",
      visits: 5,
    },
    {
      id: 18,
      name: "Emma Garcia",
      phone: "555-0018",
      frequent_order: "Oat Milk Latte",
      visits: 3,
    },
    {
      id: 19,
      name: "Mateo Lopez",
      phone: "555-0019",
      frequent_order: "Hazelnut Latte",
      visits: 1,
    },
    {
      id: 20,
      name: "Sophia Diaz",
      phone: "555-0020",
      frequent_order: "Turmeric Latte",
      visits: 2,
    },
    {
      id: 21,
      name: "Jaxon Rivera",
      phone: "555-0021",
      frequent_order: "Vietnamese Coffee",
      visits: 3,
    },
    {
      id: 22,
      name: "Aria Brooks",
      phone: "555-0022",
      frequent_order: "Cafe au Lait",
      visits: 2,
    },
    {
      id: 23,
      name: "Lucas Price",
      phone: "555-0023",
      frequent_order: "Drip Coffee",
      visits: 4,
    },
    {
      id: 24,
      name: "Zoe Bennett",
      phone: "555-0024",
      frequent_order: "Honey Lavender Latte",
      visits: 1,
    },
    {
      id: 25,
      name: "Elijah Wood",
      phone: "555-0025",
      frequent_order: "Espresso Macchiato",
      visits: 5,
    },
    {
      id: 26,
      name: "Chloe Adams",
      phone: "555-0026",
      frequent_order: "Affogato",
      visits: 3,
    },
    {
      id: 27,
      name: "Benjamin Hall",
      phone: "555-0027",
      frequent_order: "Café Bombón",
      visits: 2,
    },
    {
      id: 28,
      name: "Avery Morgan",
      phone: "555-0028",
      frequent_order: "Nitro Cold Brew",
      visits: 3,
    },
    {
      id: 29,
      name: "Logan Foster",
      phone: "555-0029",
      frequent_order: "Ristretto",
      visits: 1,
    },
    {
      id: 30,
      name: "Scarlett Gray",
      phone: "555-0030",
      frequent_order: "Irish Coffee",
      visits: 2,
    },
    {
      id: 31,
      name: "Mason Hughes",
      phone: "555-0031",
      frequent_order: "Spanish Latte",
      visits: 4,
    },
    {
      id: 32,
      name: "Luna Cooper",
      phone: "555-0032",
      frequent_order: "Café con Leche",
      visits: 3,
    },
    {
      id: 33,
      name: "Carter Allen",
      phone: "555-0033",
      frequent_order: "Butter Coffee",
      visits: 2,
    },
    {
      id: 34,
      name: "Hazel Bailey",
      phone: "555-0034",
      frequent_order: "Iced Mocha",
      visits: 5,
    },
    {
      id: 35,
      name: "Grayson Wright",
      phone: "555-0035",
      frequent_order: "Dark Roast",
      visits: 2,
    },
    {
      id: 36,
      name: "Ellie Young",
      phone: "555-0036",
      frequent_order: "Iced Cappuccino",
      visits: 3,
    },
    {
      id: 37,
      name: "Lucas King",
      phone: "555-0037",
      frequent_order: "Cold Brew with Cream",
      visits: 4,
    },
    {
      id: 38,
      name: "Camila Scott",
      phone: "555-0038",
      frequent_order: "Rose Latte",
      visits: 1,
    },
    {
      id: 39,
      name: "Aiden Turner",
      phone: "555-0039",
      frequent_order: "Almond Milk Latte",
      visits: 2,
    },
    {
      id: 40,
      name: "Stella Murphy",
      phone: "555-0040",
      frequent_order: "Golden Milk",
      visits: 1,
    },
  ]);
}
